denoise:
  k: 1
  sigma: 0.0
grid:
  rows: 3
  cols_per_row:
  - 17
  - 17
  - 17
  anchor_left:
  - - 172
    - 138
  - - 135
    - 787
  - - 123
    - 1450
  anchor_right:
  - - 2686
    - 138
  - - 2705
    - 787
  - - 2721
    - 1450
  roi:
    w: 150
    h: 200
yellow_hsv:
  lower:
  - 10
  - 140
  - 30
  upper:
  - 50
  - 255
  - 255
morph:
  open_k: 1
  close_k: 1
  erode_k: 1
  erode_iter: 0
  keep_largest: true
rod:
  vertical_tol_deg: 90.0
  min_bbox_area: 400
junction:
  rod_bottom_percentile: 98.0
  win_up: 60
  win_down: 40
  strip_offset_x: 24
  strip_half_width: 12
white:
  S_max: 40
  V_min: 120
split:
  smooth_half_win: 3
  min_rows_above: 3
  min_rows_below: 3
  min_delta_white: 0.2
band:
  y0: 3
  y1: 30
  half_width: 30
  H_low: 0
  H_high: 179
  smooth_half_win: 2
  S_thr: 30
  min_width: 10
  max_width: 0
  use_median: false
offset:
  offset_base: 4
  offset_tol: 12
height:
  delta_up: 20
overlay:
  ok_bgr:
  - 0
  - 200
  - 0
  ng_bgr:
  - 0
  - 0
  - 220
  line_width: 3
dbg:
  show_roi: false
  show_mask: false
  show_strips: false
  show_band: false
